# -*- coding: utf-8 -*-
"""Omnivoice Cloner Free .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JN5dCfxlAFvb6MuUjWuRCSVBsoxl86G4

# **Installing Python 3.10.11**
"""

# @title
!sudo apt-get update -y
!sudo apt-get install python3.10 python3.10-distutils python3.10-venv -y
!curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10
!python3.10 --version

"""# **Clone**"""

# Commented out IPython magic to ensure Python compatibility.
# @title
# %cd /content
!git clone https://huggingface.co/spaces/k2-fsa/OmniVoice
# %cd OmniVoice

"""# **Requirements**"""

# @title
!python3.10 -m pip install -r requirements.txt
!python3.10 -m pip install spaces

# @title
!apt-get update -qq
!apt-get install -y ffmpeg

"""# **Change in App File**"""

# @title
# Update app.py launch line to add share=True

file_path = "app.py"   # change path if app.py is in another folder

with open(file_path, "r", encoding="utf-8") as f:
    content = f.read()

content = content.replace(
    "demo.queue().launch()",
    "demo.queue().launch(share=True)"
)

with open(file_path, "w", encoding="utf-8") as f:
    f.write(content)

print("✅ app.py updated successfully with share=True")

# @title
file_path = "/content/OmniVoice/omnivoice/models/omnivoice.py"

with open(file_path, "r") as f:
    code = f.read()

old = 'return self._asr_pipe(audio_input)["text"].strip()'

new = '''import numpy as np
        if isinstance(audio_input, dict):
            audio_array = np.array(audio_input["array"], dtype=np.float32)
            sr = audio_input["sampling_rate"]
        else:
            audio_array = np.array(audio_input[0], dtype=np.float32)
            sr = audio_input[1]
        return self._asr_pipe({"array": audio_array, "sampling_rate": sr})["text"].strip()'''

code = code.replace(old, new)

with open(file_path, "w") as f:
    f.write(code)

print("Patch applied correctly ✅")

"""# **Main Code**"""

!python3.10 app.py